### ISSUE TITLE
The src folder might not be needed

### ISSUE THREAD

**Issue by imesh** [abhishek0198/test-framework#3]
AFAIU if a src folder is used, the following command would not work properly:
```
go get github.com/abhishek0198/test-framework
cd $GOPATH/src/github.com/abhishek0198/test-framework
go build
```

**Comment by abhishek0198** [comment]
I see, I did not know about this. I looked for the standard go project architecture and used it. Will look for options to get rid of src and start with root level packages.

**Comment by abhishek0198** [comment]
Fixed.
