### ISSUE TITLE
Overall test results

### ISSUE THREAD

**Issue by Vishanth** [abhishek0198/test-framework#7]
The output file at the moment doesn't have overall test result of each product at the end of the test run, which I think is very important because if you are testing a big list of products, it is hard to find the status of each product in a large logs trace.

**Comment by abhishek0198** [comment]
@Vishanth Added this capability. Here is a sample result from the latest run:

========================TEST RUN RESULT  ===================
2016/08/12 00:36:24 main.go:100: Test: 'wso2esb:4.9.0:puppet:default', Result: Pass
2016/08/12 00:36:24 main.go:100: Test: 'wso2mb:3.1.0:puppet:default', Result: Fail
2016/08/12 00:36:24 main.go:100: Test: 'wso2esb:4.9.0:default:default', Result: Pass
=============================================================
