### ISSUE TITLE
Readme file is not updated

### ISSUE THREAD

**Issue by pubudu538** [abhishek0198/test-framework#8]
Better to correct following mismatches.

1. We don't need to build the project once we change the test-config.json. 
2. I could not find any bin directory as it says to use ./main.
3. We can run ./test-framework to launch the test framework.

**Comment by abhishek0198** [comment]
Thanks @pubudu538  for pointing this out, I have corrected the readme to address these issues. 

- Abhishek

**Comment by chamilad** [comment]
The readme seems to be still outdated. I suggest to keep this opened until the project reaches maturity, to constantly update the README.
