### ISSUE TITLE
No validation to check the existence of the docker image

### ISSUE THREAD

**Issue by pubudu538** [abhishek0198/test-framework#9]
There is no validation to check whether the docker image is there before running the docker image. Please do check all the validations. There can be situations where docker images are not built successfully.

**Comment by abhishek0198** [comment]
Thanks @pubudu538  for pointing it out, I have added the fix. Closing this for now, feel free to reopen if the fix does not address the issue.

**Comment by chamilad** [comment]
Looks like the execution of the test framework stops if the docker image already exists. IMO that's a too frequent validation to fail. It would be better to pause and ask the user whether to overwrite the docker image.
